### ISSUE TITLE
Slightly different base patterns

### ISSUE THREAD

**Issue by robinjoseph08** [logrusorgru/grokky#4]
I'm looking to use this package to port over some Logstash functionality into a new Go codebase, but when I copy over my grok patterns, they don't seem to be matching the same way. I checked, and it looks like the [base patterns](https://github.com/logrusorgru/grokky/blob/47edf017d42ca3e04d284175020fbc7aa9200384/base.go#L45-L150) in this repo are slightly different from [Logstash's implementation](https://github.com/logstash-plugins/logstash-patterns-core/blob/a1f582bb39a6ff3db323d27614e09200830e5e26/patterns/grok-patterns) of it.

For example, here is this repo's `IPV4` pattern:

```
(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))
```

And here's Logstash's:

```
(?<![0-9])(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))(?![0-9])
```

The result of this is that when an IP is matched, it isn't consumed from the string which through. I didn't dig into why the pattern behaves that way (since it's pretty complicated), but either way, it seems like undesired behavior.

If I put up a PR to switch everything to Logstash's implementation of the patterns, would that be merged in? What do you think?

**Comment by logrusorgru** [comment]
Hi, thank you for the issue.

The Logstash uses [Oniguruma](https://github.com/kkos/oniguruma) regexp engine. The grokky based on Go standard implementation of the [RE2](https://github.com/google/re2) regexp. Thus, some capabilities of the Oniguruma can't be used. Such as look ahead, look behind, etc.

Other words, Omiguruma patterns are incompatible.

> The result of this is that when an IP is matched, it isn't consumed from the string which through. I didn't dig into why the pattern behaves that way (since it's pretty complicated), but either way, it seems like undesired behavior.

Yep, this is misbehavior. To be honest, I never [test the base patterns](https://github.com/logrusorgru/grokky/blob/47edf017d42ca3e04d284175020fbc7aa9200384/base_test.go#L53). And they might work wrong.

Please, provide an example doesn't work and let's catch and fix it.

As I understand the leading `(?:` means match but don't capture. And result depends on your example, since the Grokky has some internal wrapping with capture group in some cases. As I remember, I used to add the `(?:` to avoid one more useless capture group.
